export interface PhraseGroup {
  voiceId: string;
  voiceName: string;
  persona: string;
  personaDescription: string;
  phrases: string[];
}

export const VOICE_PHRASE_GROUPS: PhraseGroup[] = [
  {
    voiceId: "sarah",
    voiceName: "Sarah",
    persona: "Warm & Supportive Friend",
    personaDescription: "Like a caring best friend who always knows the right thing to say",
    phrases: [
      "Hey, you're doing amazing. I just wanted you to know that.",
      "Take a deep breath. You've handled harder things before.",
      "I'm proud of you for showing up today. That takes courage.",
      "Remember, it's okay to go at your own pace. You're not behind.",
      "You bring something unique to everything you do. Don't forget that.",
      "Whatever you're working on, it matters. And so do you.",
      "Even small steps count. You're still moving forward.",
      "It's okay to not have all the answers. You're figuring it out.",
      "Your effort is seen, even when it doesn't feel like it.",
      "You're allowed to take breaks. Rest is part of the process.",
      "Trust yourself. You've made it through every challenge so far.",
      "Be patient with yourself. Growth takes time.",
      "You're doing better than you think. Really.",
      "This moment will pass, and you'll be okay.",
      "Your presence makes a difference. Don't underestimate it.",
      "It's okay to feel overwhelmed. Just take it one thing at a time.",
      "You don't have to be perfect to be valuable.",
      "Every day you try is a win. Remember that.",
      "You're stronger than you give yourself credit for.",
      "Take a moment to appreciate yourself. You deserve it.",
      "Progress isn't always visible, but it's happening.",
      "You're not alone in this. I believe in you.",
      "It's okay to ask for help. That's actually really brave.",
      "You've got this, even when it doesn't feel like it.",
      "Your feelings are valid. All of them.",
      "Remember to celebrate the small victories too.",
      "You're learning and growing every single day.",
      "It's okay to start over. Every expert was once a beginner.",
      "Your best is always enough. Always.",
      "Keep going. The world needs what you have to offer.",
    ],
  },
  {
    voiceId: "bill",
    voiceName: "Bill",
    persona: "Calm Mentor",
    personaDescription: "A steady, reassuring voice of experience and wisdom",
    phrases: [
      "Stay the course. You're building something meaningful here.",
      "Focus is a skill. Every time you practice it, you get stronger.",
      "The work you're doing now is an investment in your future self.",
      "Clear mind, steady hands. You've got the capability for this.",
      "One task at a time. That's how great things get accomplished.",
      "Distractions will come and go. Your focus remains.",
      "You're more prepared for this than you realize.",
      "Trust the process. Results follow consistent effort.",
      "Every professional was once an amateur. Keep going.",
      "Your attention is valuable. Spend it wisely.",
      "Patience and persistence will take you far.",
      "The path to mastery is paved with practice.",
      "Stay grounded. Your work speaks for itself.",
      "Challenges are opportunities in disguise. Embrace them.",
      "You're developing skills that will serve you for life.",
      "Steady progress beats scattered bursts every time.",
      "Your dedication is the foundation of your success.",
      "Stay present with the task at hand. The rest will follow.",
      "Confidence comes from competence, and you're building both.",
      "The best time to focus is right now.",
      "You have everything you need to succeed in this moment.",
      "Small disciplines lead to great achievements.",
      "Keep your eyes on your own paper. Your path is yours.",
      "Excellence is a habit you're cultivating daily.",
      "Your consistency is your competitive advantage.",
      "Stay committed to your goals, but flexible in your approach.",
      "Every minute of focused work moves you forward.",
      "You're exactly where you need to be on your journey.",
      "Trust your training. You've prepared for this.",
      "Your potential is limitless. Keep reaching.",
    ],
  },
  {
    voiceId: "george",
    voiceName: "George",
    persona: "Wise Grandfather",
    personaDescription: "A gentle, wise soul with life experience and warmth",
    phrases: [
      "You know, in all my years, I've learned that showing up is half the battle. And here you are.",
      "Take it from an old timer - the best things in life take patience. You're doing fine.",
      "Back in my day, we'd say 'slow and steady wins the race.' That still holds true.",
      "I've seen a lot of people give up too soon. Don't be one of them. You've got something special.",
      "Remember, every expert was once a beginner. Keep at it, young one.",
      "The greatest achievements come from ordinary people who refused to quit.",
      "In my experience, the ones who succeed are the ones who keep showing up.",
      "Don't rush yourself. Good things take time, like a fine wine.",
      "I believe in you, and I've learned to trust my instincts over the years.",
      "Life has taught me that perseverance pays off. Just keep going.",
      "You're writing your own story. Make it one worth telling.",
      "The best investment you can make is in yourself. You're doing that right now.",
      "I've weathered many storms. Each one made me stronger. Same goes for you.",
      "Take a moment to breathe. I've found the answers come when we're still.",
      "You remind me of the dreamers who changed the world. Keep dreaming.",
      "Every setback is a setup for a comeback. Remember that.",
      "In my lifetime, I've seen impossible things become possible. So can your goals.",
      "The measure of a person isn't their struggles, but how they rise above them.",
      "You've got more wisdom in you than you realize. Trust it.",
      "Time moves fast. Appreciate this moment and the growth it brings.",
      "I've learned that kindness to yourself is the first step to success.",
      "Your journey is unique. Don't compare it to anyone else's.",
      "The seeds you plant today will bloom tomorrow. Keep planting.",
      "Age has taught me that worrying solves nothing. Focus on what you can control.",
      "You've got a good head on your shoulders. Use it.",
      "Every day is a chance to write a new chapter. Make today count.",
      "I've seen people accomplish amazing things. You're one of those people.",
      "Life's too short for regrets. Do your best and let the rest go.",
      "You're building a life you can be proud of. One day at a time.",
      "Remember, the view from the mountain top is worth the climb.",
    ],
  },
  {
    voiceId: "charlie",
    voiceName: "Charlie",
    persona: "Chill Hippy Philosopher",
    personaDescription: "A relaxed, free-spirited soul with unconventional wisdom",
    phrases: [
      "Hey dude, just flow with it. You're doing cosmic work over there.",
      "The universe is vibing with you right now. Can you feel it?",
      "Man, you're like a butterfly. Always transforming, always beautiful.",
      "Just breathe, friend. The answers are already inside you.",
      "You're connected to something bigger than yourself. Trust the journey.",
      "The only moment that exists is right now. And right now, you're killing it.",
      "Your energy is electric, my friend. Channel it into your work.",
      "Don't stress the small stuff. In the cosmic scheme, it's all small stuff.",
      "You're exactly where the universe needs you to be. Wild, right?",
      "Let go of what you can't control. Focus on your own vibration.",
      "Every breath is a fresh start. How beautiful is that?",
      "You're not just doing work, you're creating ripples in the universe.",
      "Be like water, friend. Adapt, flow, overcome.",
      "Your consciousness is expanding every moment. That's pretty groovy.",
      "The journey is the destination, man. Enjoy every step.",
      "You've got this cosmic energy flowing through you. Use it wisely.",
      "Life is just a series of nows. Make this now count.",
      "Your thoughts create your reality. Think beautiful things.",
      "We're all made of stardust. You're literally a piece of the universe working.",
      "Don't fight the current. Let it carry you where you need to go.",
      "Every challenge is the universe testing how badly you want it.",
      "You're not separate from nature. You are nature, creating.",
      "Peace comes from within. And you've got plenty to share.",
      "Your potential is infinite, like the cosmos. How cool is that?",
      "Sometimes the best thing to do is just be. You know?",
      "You're on your own unique path. That's beautiful, man.",
      "The universe conspires to help those who believe. Keep believing.",
      "Life is a dance. Don't worry about the steps, just feel the music.",
      "You're radiating good vibes right now. Keep that energy flowing.",
      "Remember, we're all just walking each other home. You're never alone.",
    ],
  },
];

export const MODE_PHRASES = {
  gentle: [
    "You're doing great. Just keep going, one step at a time.",
    "It's okay to take a breath. You've got this.",
    "Remember, progress is more important than perfection.",
    "You're exactly where you need to be right now.",
    "Be gentle with yourself. You're doing your best.",
    "Small steps still move you forward.",
    "You matter, and your efforts matter too.",
    "Take a moment to appreciate how far you've come.",
    "It's okay to pause. Rest is productive too.",
    "You're capable of amazing things.",
    "Your journey is unique and valuable.",
    "Every effort you make counts, even the small ones.",
    "You're learning and growing with each passing moment.",
    "It's okay to not be okay sometimes.",
    "Your feelings are valid and important.",
    "Take things at your own pace. There's no rush.",
    "You're doing better than you think.",
    "Remember to breathe and be kind to yourself.",
    "Your presence makes a difference.",
    "You're worthy of all good things.",
    "Progress looks different for everyone. You're on track.",
    "Allow yourself grace during difficult moments.",
    "You're stronger than you realize.",
    "Each new day brings new possibilities.",
    "Trust yourself. You know more than you think.",
    "Your best effort is always enough.",
    "It's okay to take breaks when you need them.",
    "You're making progress, even when you can't see it.",
    "Be patient with yourself as you grow.",
    "You are enough, just as you are.",
  ],
  motivating: [
    "Let's go! You've got the power to crush this!",
    "Focus up! You're unstoppable when you're in the zone.",
    "Every task you complete brings you closer to your goals!",
    "You're a productivity machine! Keep that momentum going!",
    "No distractions can stop you when you're this focused!",
    "You're building something amazing, one task at a time!",
    "Energy high, distractions low. You've got this!",
    "This is your moment. Make it count!",
    "Push through! The finish line is closer than you think!",
    "You're in control. Own this moment!",
    "Champions are made in moments like this!",
    "Your dedication is about to pay off. Keep going!",
    "Nothing can stop you when you're in the zone!",
    "You were born for this. Show them what you've got!",
    "Every second of focus brings you closer to success!",
    "Rise up! This is your time to shine!",
    "Your potential is unlimited. Unleash it!",
    "Hard work beats talent when talent doesn't work hard!",
    "You're making magic happen right now!",
    "Stay hungry, stay focused, stay unstoppable!",
    "The only limit is the one you set for yourself!",
    "You're writing your success story right now!",
    "Believe it, achieve it. You've got what it takes!",
    "Excellence is not an act, it's a habit. Keep building!",
    "Your future self will thank you for this effort!",
    "Attack this day with energy and purpose!",
    "You're not just working, you're winning!",
    "Every challenge is an opportunity to grow stronger!",
    "Stay relentless. Success is just around the corner!",
    "You're a force of nature. Nothing can hold you back!",
  ],
  calm: [
    "Breathe in calm, breathe out tension.",
    "Let your thoughts flow like a gentle stream.",
    "Find peace in this present moment.",
    "Your mind is clear, your focus is steady.",
    "Allow yourself to simply be.",
    "Embrace the stillness within.",
    "Each breath brings you deeper into focus.",
    "You are centered and at peace.",
    "Let go of what you cannot control.",
    "In this moment, all is well.",
    "Peace flows through you like a quiet river.",
    "Your inner calm is your greatest strength.",
    "Rest in the tranquility of this moment.",
    "Stillness speaks louder than chaos.",
    "Find your center and breathe.",
    "Serenity is always within your reach.",
    "Let peace wash over you like gentle waves.",
    "Your calm presence is a gift to yourself.",
    "In stillness, you find clarity.",
    "Allow tension to melt away with each breath.",
    "You are grounded, centered, and at ease.",
    "The present moment is all that exists.",
    "Peace begins with a single, conscious breath.",
    "Your thoughts are clouds, let them drift by.",
    "Find comfort in the rhythm of your breathing.",
    "Tranquility flows naturally when you allow it.",
    "In this quiet moment, wisdom emerges.",
    "Your spirit is calm like still water.",
    "Embrace the gentle silence within.",
    "All you need is this breath, this moment.",
  ],
};

export function getPhrasesForVoice(voiceId: string): string[] {
  const group = VOICE_PHRASE_GROUPS.find((g) => g.voiceId === voiceId);
  return group ? group.phrases : VOICE_PHRASE_GROUPS[0].phrases;
}

export function getRandomPhrase(voiceId: string, mode: string, excludePhrase?: string): string {
  let phrases: string[];

  if (voiceId === "random") {
    const allVoicePhrases = VOICE_PHRASE_GROUPS.flatMap((g) => g.phrases);
    phrases = allVoicePhrases;
  } else {
    phrases = getPhrasesForVoice(voiceId);
  }

  const filteredPhrases = excludePhrase
    ? phrases.filter((p) => p !== excludePhrase)
    : phrases;

  return filteredPhrases[Math.floor(Math.random() * filteredPhrases.length)];
}

export function getVoicePersona(voiceId: string): { persona: string; description: string } | null {
  const group = VOICE_PHRASE_GROUPS.find((g) => g.voiceId === voiceId);
  if (!group) return null;
  return { persona: group.persona, description: group.personaDescription };
}
